# -*- coding: utf-8 -*-
"""Copy of time_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucFPy2BSADadKbzn1fXOb1LyytLed5-R
"""

#!pip install tensorflow
#%%

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
import os

try:
    df = pd.read_csv('C:/Users/nupur/computer/Desktop/Group-7-PDFM/Project/data/merged_data_unemployment_r9.csv')
    print("Columns in dataset:", df.columns.tolist())

    # Filter counties
    selected_counties = ['Los Angeles County', 'Alameda County','Pinal County','Clark County','Maricopa County','Orange County','San Diego County','Washoe County']
    filtered_df = df[df['county'].isin(selected_counties)].copy()

    if filtered_df.empty:
        raise ValueError("No data found for specified counties")

except Exception as e:
    print(f"Error: {e}")
    raise

print(filtered_df)

time_columns = df.filter(regex='^(19|20)').columns.tolist()
print(time_columns)

last_6_months = time_columns[-6:]

window_size = 100
prediction_horizon = 6
n_features = 1
epochs = 10
batch_size = 32

#%%
def create_sequences(data, window_size, horizon, step=1):
    """Create sequences with configurable step size"""
    X, y = [], []
    for i in range(0, len(data) - window_size - horizon + 1, step):
        X.append(data[i:i+window_size])
        y.append(data[i+window_size:i+window_size+horizon])
    return np.array(X), np.array(y)

for county_name in selected_counties:
    print(f"\n{'='*40}\nProcessing {county_name}\n{'='*40}")

    # Extract time series data
    county_data = filtered_df[filtered_df['county'] == county_name]
    time_series = county_data.filter(regex='^(19|20)').values.astype(np.float32)
    ts_data = time_series.reshape(-1, 1)

    # Train/test split
    train_data = ts_data[:406]
    test_data = ts_data[406-100:406+6]

    # Model setup
    model = tf.keras.Sequential([
        tf.keras.layers.LSTM(64, return_sequences=True,
                            input_shape=(window_size, n_features)),
        tf.keras.layers.LSTM(64, return_sequences=True),
        tf.keras.layers.LSTM(32, return_sequences=False),
        tf.keras.layers.Dense(prediction_horizon)
    ])
    model.compile(optimizer='adam', loss='mse')

    # Training loop with progress tracking
    current_window = window_size
    iteration = 1
    while current_window <= 406 - prediction_horizon:
        current_data = train_data[:current_window]
        X, y = create_sequences(current_data, window_size, prediction_horizon, step=1)

        if len(X) > 0:
            print(f"\nIteration {iteration}:")
            print(f"Training Window: {current_window} months")
            print(f"Prediction Horizon: {prediction_horizon} months")
            print(f"Generated Sequences: {len(X)}")

            model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=0)
            iteration += 1

        current_window += 1  # Changed from += prediction_horizon to +=1 for 1-month steps

    # Final prediction and evaluation
    X_test = train_data[-window_size:].reshape(1, window_size, n_features)
    y_true = ts_data[406:406+6]
    y_pred = model.predict(X_test).flatten()

    # Calculate metrics
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)

    # Final report
    print(f"\n{'='*40}")
    print(f"{county_name} Final Results:")
    print(f"Total Training Months Used: {current_window-1}")  # -1 because of last increment
    print(f"Final Test Months: {len(y_true)}")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAE: {mae:.4f}")
    print(f"{'='*40}")

    # Plotting (unchanged)
    plt.figure(figsize=(12,6))
    plt.plot(last_6_months, y_true, 'o-', label='Actual')
    plt.plot(last_6_months, y_pred, 'x--', label='Predicted')
    plt.title(f'{county_name} Unemployment Prediction')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()





